vich_uploader:
    db_driver: orm

    mappings:
        chamber_images:
            uri_prefix: '%app.path.chamber_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.chamber_images%'